@startuml

skinparam object {
    BackgroundColor Snow
    BorderColor Purple
    ArrowColor Purple
}

object PaymentType{
    CARD,
    CASH,
    PAYPAL,
    OTHER
}

object Command{
    <u>idCommand</u> : Int auto_increment
    deliveryDate : LocalDateTime?
    status : CommandStatusType?
    clientId : Long
    totalPrice : Double
    articleWrappers : List<ArticleWrapper>
    paymentAmount : Double
    paymentType : PaymentType
}

object ArticleWrapper {
    <u>idCommandIngredient</u> : Int auto_increment
    article : Article
    count : Int
    totalArticleWrapperPrice : Double
    status : ArticleWrapperStatus
}

object Client{
    <u>idClient</u> : Long auto_increment
    firstname : String not null
    lastname : String?
    phoneNumber : Int?
    fidelityPoint : Int default 0
}

object ArticleWrapperStatus{
    IN_PROGRESS,
    DONE,
    CANCELED,
}

object CommandStatusType{
    IN_PROGRESS,
    DONE,
    DELIVERED,
    CANCELED,
    PAYED
}

object Article{
    <u>idArticle</u> : Int auto_increment
    label : String
    price : Double
    composedIngredients : List<IngredientWrapper>
}

object ArticleCategory {
    SALTED,
    SWEET,
    OTHER
}

object IngredientWrapper{
    <u>idIngredientWrapper</u> : Int auto_increment
    ingredient : Ingredient
    quantity : Double
    quantityType : QuantityType
}

object RecipeWrapper{
    <u>idRecipeWrapper</u> : Int auto_increment
    ingredient : Ingredient
    quantity : Double
    quantityType : QuantityType
}

object QuantityType {
    ML,
    L,
    G,
    KG
}

object Ingredient{
    <u>idIngredient</u> : Int auto_increment
    label : String
    price : Double
}

object Provider{
    <u>idProvider</u> : Int auto_increment
    label : String
    localization : String?
}

object Stock{
    <u>idStock</u> : Int auto_increment
    lastUpdateDate : LocalDateTime
    label : String (name)
    IngredientWrappers : List<IngredientWrapper>
}

Command "1" -right- "1" PaymentType : a
Command "1" --left- "1" Client : pour
Command "1" --down- "1" ArticleWrapper : possède
Command "1" --up- "1" CommandStatusType : a
ArticleWrapper "1" --right- "1" ArticleWrapperStatus : a
Article "1..n" -left- "1" ArticleCategory : est
Article "1..n" -right- "1" ArticleWrapper : contient
Ingredient "1..n" -right- "1" Provider : de
IngredientWrapper "1..n" -right- "1" Ingredient : de
IngredientWrapper "1..n" -up- "1..n" Stock : a
IngredientWrapper "1" -down- QuantityType : a
RecipeWrapper "1..n" -up- "1" Ingredient : de
RecipeWrapper "1..n" -down- "1..n" Article : a
RecipeWrapper "1" -left- QuantityType : a

@enduml

